### ISSUE TITLE
Build all packages in Fedora with sdl12-compat instead of SDL 1.2...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#78]
Fedora project's proposal:

https://fedoraproject.org/wiki/Changes/SDL12onSDL2

Thread with discussion of package lists:

https://twitter.com/icculus/status/1398319367222444034

Some initial automation work:

https://github.com/libsdl-org/sdl12-compat/issues/34#issuecomment-847326194

**Comment by icculus** [comment]
OpenSceneGraph took like 12 hours to build; might need to use a more-powerful machine for this.  :)

Getting a _lot_ of failures to find the library at link time, so something is probably wrong with the script still. Here's SDL_image failing...

```
/bin/sh ./libtool   --mode=link gcc  -I/usr/include/libpng16  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -no-undefined -release 1.2 -version-info 8:4:8 -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -o libSDL_image.la -rpath /usr/lib64 IMG.lo IMG_bmp.lo IMG_gif.lo IMG_jpg.lo IMG_lbm.lo IMG_pcx.lo IMG_png.lo IMG_pnm.lo IMG_tga.lo IMG_tif.lo IMG_xcf.lo IMG_xpm.lo IMG_xv.lo IMG_webp.lo  -lpng -lz  -lSDL -lpthread 
libtool: link: gcc -shared  .libs/IMG.o .libs/IMG_bmp.o .libs/IMG_gif.o .libs/IMG_jpg.o .libs/IMG_lbm.o .libs/IMG_pcx.o .libs/IMG_png.o .libs/IMG_pnm.o .libs/IMG_tga.o .libs/IMG_tif.o .libs/IMG_xcf.o .libs/IMG_xpm.o .libs/IMG_xv.o .libs/IMG_webp.o   -lpng -lz -lSDL -lpthread -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -m64 -mtune=generic -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now   -Wl,-soname -Wl,libSDL_image-1.2.so.0 -o .libs/libSDL_image-1.2.so.0.8.4
/usr/bin/ld: cannot find -lSDL
collect2: error: ld returned 1 exit status
make: *** [Makefile:389: libSDL_image.la] Error 1
```

**Comment by lanodan** [comment]
Landed on this kind of issue as well when building SDL_image.

This is because https://github.com/libsdl-org/sdl12-compat/blob/main/CMakeLists.txt#L63 names it `libSDL-1.2.so` and both `sdl-config` and `sdl12_compat.pc` are only poiting towards a `libSDL.so`/`libSDL.so.*`.

I think it would be better to target it as `libSDL.so` to avoid having to change legacy programs having their own detection code but it looks like you'd prefer fixing `sdl-config`&`sdl12_compat.pc`.

**Comment by sezero** [comment]
We do need our CMake'ry to additionally create a `libSDL-1.2.so` symlink.

**Comment by sezero** [comment]
> We do need our CMake'ry to additionally create a `libSDL.so` (or `libSDL.dylib`) symlink.
> Just did that in linux and darwin standalone makefiles as of [f6a60d6](https://github.com/libsdl-org/sdl12-compat/commit/f6a60d6534a16308cfc22f7b0945797849efb083)
> 
> Someone better familiar than me with cmake should do the same in CMakeLists.txt

This has been fixed in git for some time. What issues remain to be fixed in this bug entry?

**Comment by icculus** [comment]
> What issues remain to be fixed in this bug entry?

I think I just need to leave the Fedora virtual machine cooking all the packages and see what else complains at this point. I'm starting that over now, but it runs for a looooong time.

**Comment by icculus** [comment]
(Just realized the virtual machine had 2 gigabytes of RAM and 1 processor core available to it. Pumped that up to 16 gigs and 8 cores, so hopefully that'll help if the builds parallelize, and I'll move it to a more-powerful machine if necessary.)

**Comment by icculus** [comment]
Failure in brutalchess package...

```
/usr/include/SDL/SDL_opengl.h:52:10: fatal error: GL/glu.h: No such file or directory
```

...I assume this is a dependency issue and not an sdl12-compat bug...?

**Comment by sezero** [comment]
> ```
> /usr/include/SDL/SDL_opengl.h:52:10: fatal error: GL/glu.h: No such file or directory
> ```
> 
> ...I assume this is a dependency issue and not an sdl12-compat bug...?

Well, yeah..

**Comment by sezero** [comment]
I think `mesa-libGLU-devel` needs to be installed for it.

**Comment by icculus** [comment]
This is more for @Conan-Kudo, specifically: do we need sdl12-compat to depend on GLU? Surely we don't expect every package that `#include`s SDL_opengl.h to depend on it?

Did the real 1.2 depend on it, or do these packages generally build by luck of having GLU installed already?

**Comment by sezero** [comment]
> This is more for @Conan-Kudo, specifically: do we need sdl12-compat's RPM to depend on GLU? Surely we don't expect every package that `#include`s SDL_opengl.h to depend on it?

Well, that's irrelevant IMO. SDL-1.2 header depends on glu.h and programs _might_
as well depend on that, we can't know. Besides. sdl12-compat-devel will depend on
glu.h, not the main sdl12-compat rpm.

> Did the real 1.2 depend on it, 

yes

>  or do these packages generally build by luck of having GLU installed already?

They should have installed the dependency.

**Comment by icculus** [comment]
This is the current fail list, but a cursory glance shows a lot of these are failing for non-SDL reasons (one failed to build because it couldn't find libasound headers in unrelated code, etc, which might be a flaw in the build script I'm using or that the sdl12-compat-devel package doesn't pull in ALSA dependencies--because it doesn't use ALSA!--when I assume SDL 1.2-devel did pull in the dependency because SDL 1.2 can be built with ALSA support). Those items are fedora problems and should probably be cleaned up but are likely not related to the sdl12-compat-devel package for the most part.

Also worth noting: perl-SDL wasn't on the list of packages to build for whatever reason, but _does_ depend on SDL 1.2 and we fixed bugs in sdl12-compat for it...so there's probably something about how we generate the list of packages to test that needs to be revisited.

Here were the ones that failed for any reason. This isn't necessarily a TODO list for us, just documenting this.

```
SDL12_COMPAT_FAILED: ClanLib1
SDL12_COMPAT_FAILED: asterisk
SDL12_COMPAT_FAILED: berusky
SDL12_COMPAT_FAILED: berusky2
SDL12_COMPAT_FAILED: boswars
SDL12_COMPAT_FAILED: brutalchess
SDL12_COMPAT_FAILED: crossfire-client
SDL12_COMPAT_FAILED: enigma
SDL12_COMPAT_FAILED: erlang-esdl
SDL12_COMPAT_FAILED: fawkes
SDL12_COMPAT_FAILED: gearhead1
SDL12_COMPAT_FAILED: glob2
SDL12_COMPAT_FAILED: gnujump
SDL12_COMPAT_FAILED: grafx2
SDL12_COMPAT_FAILED: libzia
SDL12_COMPAT_FAILED: lincity-ng
SDL12_COMPAT_FAILED: mlt
SDL12_COMPAT_FAILED: nagi
SDL12_COMPAT_FAILED: nethack-vultures
SDL12_COMPAT_FAILED: opencity
SDL12_COMPAT_FAILED: quake3
SDL12_COMPAT_FAILED: rcssserver3d
SDL12_COMPAT_FAILED: sage
SDL12_COMPAT_FAILED: simcoupe
SDL12_COMPAT_FAILED: simspark
SDL12_COMPAT_FAILED: sms_ntsc
SDL12_COMPAT_FAILED: snes_ntsc
SDL12_COMPAT_FAILED: sopwith
SDL12_COMPAT_FAILED: soundtracker
SDL12_COMPAT_FAILED: tremulous
SDL12_COMPAT_FAILED: tvtime
SDL12_COMPAT_FAILED: uboot-tools
SDL12_COMPAT_FAILED: valyriatear
SDL12_COMPAT_FAILED: xgrav
SDL12_COMPAT_FAILED: xwax
```

**Comment by icculus** [comment]
Log files from all the failed builds:

[sdl12-compat-fedora-failed-builds.tar.gz](https://github.com/libsdl-org/sdl12-compat/files/6681696/sdl12-compat-fedora-failed-builds.tar.gz)

**Comment by icculus** [comment]
I can't see what failed in grafx2, libzia, mlt, rcssserver3d, sms_ntsc, snes_ntsc, sopwith, soundtracker, or uboot-tools. But here's the rest of the details, real fast:

- ClanLib1 fails with an ALSA thing, but on second glance it doesn't complain about not finding the headers, but maybe an incompatibility or something?
- asterisk fails to find /usr/bin/perl at startup and immediately gives up; build environment issue or the script, I guess.
- berusky looks like it's just broken with newer compilers and maybe hasn't been built recently? berusky2 couldn't find OpenGL during configure and gave up.
- fawkes fails because it can't file the alsa-lib-devel package
- gearhead1 tries unsuccessfully to link with -lX11
- **lincity-ng has a possible sdl12-compat bug with iconv_t**
- **nagi and nethack-vultures try to link against -lSDLmain. They shouldn't do that on Linux, but it _should_ be an empty static library we provide, but don't currently**
- **simcoupe and simspark don't work because they don't link to libpthread. Likely they relied on sdl-config to get that command line option? Our bug or theirs?**
- tvtime appears to need a dependency on alsa-dev; it's configure script gives up on AM_PATH_ALSA
- xwax can't find ALSA headers. Dependency issue.
- Several things (enigma, erlang-esdl, gnujump, etc) fail because this build of sdl12-compat still depends on X11 headers (since fixed to ignore them if missing), but we should make sure the packages don't _actually_ need x11-supported SDL_syswm.h to function.
- Lots of things failing because the build environment didn't pull in OpenGL (and GLU) dependencies, some failing in the configure script before actually compiling anything; those packages need to be fixed or the sdl12-compat-devel package should say it needs those dependencies, since SDL_opengl.h will include gl.h and glu.h.

**Comment by lanodan** [comment]
Well for my own tests on my pure-wayland gentoo system it ended up working quite well overall.

Noted it in https://hacktivis.me/git/blog/commit/73fcf9bb73b2cdc4a72187fab87ecee6980ad4c0.html for https://hacktivis.me/notes/pure-wayland
reproduced it there:

Works:
- formido
- heroes
- luola
- Maelstrom
- orbital-enuchs-sniper aka sniper2d
- powermanga
- rrootage
- violetland: Needed a GLVND tweak, that's only relevant for pure-wayland
- abe
- apricots
- balloonchase
- batrachians

Seems to work:
- snipes
- towbowl-tactics

Almost working:
- gltron: Resizing in the graphics settings makes key inputs doubled

Broken:
- savagewheels: Fails to initialize
- barrage: The message `creating 640x480 bitmap ... Unknown pixel format` seems to be the culprit
- clanbomber: keys are doubled
- deathchase3d: Seems to be broken, keys are doubled
- shootingstar: Fails to detect SDL_image

**Comment by Conan-Kudo** [comment]
> This is more for @Conan-Kudo, specifically: do we need sdl12-compat's RPM to depend on GLU? Surely we don't expect every package that `#include`s SDL_opengl.h to depend on it?
> 
> Did the real 1.2 depend on it, or do these packages generally build by luck of having GLU installed already?

[The old SDL-devel package declared dependencies on `alsa-lib-devel`, `mesa-libGL-devel`, `mesa-libGLU-devel`, `libX11-devel`, `libXext-devel`, `libXrandr-devel`, `libXrender-devel`](https://src.fedoraproject.org/rpms/SDL/blob/7a07323e5cec08bea6f390526f86a1ce5341596d/f/SDL.spec#_139-148)

I wasn't sure which ones I should carry over to `sdl12-compat-devel`. It seems like at least the Mesa ones are needed.

**Comment by Conan-Kudo** [comment]
I've added all of them now: https://src.fedoraproject.org/rpms/sdl12-compat/c/bf015874c4f2db63222b0c948a02be9b5c3db591

**Comment by icculus** [comment]
> I've added all of them now: https://src.fedoraproject.org/rpms/sdl12-compat/c/bf015874c4f2db63222b0c948a02be9b5c3db591

Strictly speaking, these are SDL2 dependencies; sdl12-compat just relies on SDL2's development package and OpenGL, neither of which it links directly against but needs the headers of both and dlopens them.

In theory, an app that uses ALSA directly but relies on SDL's package depending on it has a bug in its dependencies (especially as we live in a PulseAudio world and are moving towards PipeWire), but in practice, it might just be more efficient to leave sdl12-compat depending on it than touching other packages, just to avoid breaking things.

That's up to you and other Fedora maintainers. I'm happy to file bugs in the Bugzilla if you think it would be helpful; it's your call.

**Comment by Conan-Kudo** [comment]
> That's up to you and other Fedora maintainers. I'm happy to file bugs in the Bugzilla if you think it would be helpful; it's your call.

Please do file bugs! I don't want these deps here if we don't need them!

**Comment by icculus** [comment]
> Almost working:
> [...]
> Broken:
> [...]

Unless these are obvious issues that are trivially fixed, don't be afraid to open issues here for them, even if we discover it isn't an sdl12-compat bug, we probably have an obligation to take on that research.

**Comment by icculus** [comment]
> Please do file bugs! I don't want these deps here if we don't need them!

On it.  :)

**Comment by sezero** [comment]
FWIW, I agree with Ryan: The _only_ dependencies that `sdl12-compat-devel` must be:
- `glibc-devel` (obviously) for `-ldl`,
- `sdl12-compat` itself (obviously),
- `mesa-libGLU-devel` (because of `SDL_opengl.h`), which should auto-pull
  other opengl deps,
- whatever-X-package-devel that provides `X11/Xatom.h`, `X11/Xlib.h` and
  `X11/Xlib.h` for `SDL_syswm.h`.

**Comment by Conan-Kudo** [comment]
So basically we should drop `alsa-lib-devel`/`pkgconfig(alsa)`.

**Comment by Conan-Kudo** [comment]
> whatever-X-package-devel that provides `X11/Xatom.h`, `X11/Xlib.h` and
`X11/Xlib.h` for `SDL_syswm.h`.

Do you mean a third X11 header, because I only see two in `SDL_syswm.h`?

**Comment by sezero** [comment]
> Do you mean a third X11 header, because I only see two in `SDL_syswm.h`?

My bad, copy+paste error. `X11/Xatom.h`, `X11/Xlib.h` are the only two needed.

**Comment by sezero** [comment]
> So basically we should drop `alsa-lib-devel`/`pkgconfig(alsa)`.

Yes, that's what I think.

**Comment by Conan-Kudo** [comment]
Done: https://src.fedoraproject.org/rpms/sdl12-compat/c/fe09323e03ab28bb45641b60919872aad4e51193

Thanks for the feedback!

**Comment by icculus** [comment]
okay, bugs filed for things that reference ALSA directly:

- fawkes: https://bugzilla.redhat.com/show_bug.cgi?id=1974105
- tvtime: https://bugzilla.redhat.com/show_bug.cgi?id=1974106
- xwax: https://bugzilla.redhat.com/show_bug.cgi?id=1974107

It's not clear to me if simcoupe and simspark failing to link to libpthread is our fault in sdl-config, or a package bug, or a bug in those package's individual build systems.

**Comment by sezero** [comment]
> Log files from all the failed builds:
> 
> [sdl12-compat-fedora-failed-builds.tar.gz](https://github.com/libsdl-org/sdl12-compat/files/6681696/sdl12-compat-fedora-failed-builds.tar.gz)

Quickly browsed through, here is what I think:

- ClanLib1: its own rpm spec should require alsa-lib-devel
- tvtime: same as ClanLib1 above.
- xwax: same as ClanLib1 above.

- asterisk: its own rpm spec should require perl (I think)

- berusky: its own code seems to have issues (doesn't know
  what `offsetof` is?)

- berusky2: its own rpm spec should require packages gl and
  glu (might work after the latest sdl12-compat spec update,
  though.)
- boswars: same as berusky2 above.
- brutalchess: same as berusky2 above.
- crossfire-client: same as berusky2 above.
- glob2: same as berusky2 above.
- gnujump: same as berusky2 above.
- opencity: same as berusky2 above.
- quake3: same as berusky2 above.
- sage: same as berusky2 above.
- tremulous: same as berusky2 above.
- valyriatear: same as berusky2 above.
- xgrav: same as berusky2 above.

- enigma: its own rpm spec should require xproto-devel
  (might work after the latest sdl12-compat spec update,
  though.)
- erlang-esdl: same as enigma above.

- fawkes: the error _looks like_ something to do with docs
  generation, nothing to do with sdl12-compat?
```
  make: *** [/builddir/build/BUILD/fawkes-4923a6c1fda7799ad32b57f84ec9111bd716fd84/etc/buildsys/root/docs.mk:47: fawkes.luadoc] Error 127
  [...]
  RPM build errors:
  error: File not found: /builddir/build/BUILDROOT/fawkes-1.3.1-0.10.4923a6c.fc34.x86_64/usr/lib64/fawkes/plugins/flite.so
      File not found: /builddir/build/BUILDROOT/fawkes-1.3.1-0.10.4923a6c.fc34.x86_64/usr/lib64/fawkes/plugins/flite.so
```
- gearhead1: its own rpm spec should require xlib-devel
  (seems to want linking with `-lX11`, although there are
  other linkage warnings about missing `crtbegin.o` and
  `crtend.o`)

- nagi: actually this is sdl12-compat's fault: no libSDLmain.a
  (even though nagi itself shouldn't have required that.)
- nethack-vultures: same as nagi above.

- simcoupe: missing pthread symsols - possibly not linking with
  `-lpthread` but mistakenly relying on `SDL_LIBS` to provide it?
  Not really sdl12-compat's fault.
- simspark: same as simcoupe above.

- lincity-ng: Not sure what this is about:
```
  C++ ./build/x86_64-redhat-linux-gnu/optimize/src/gui/Child.o.
  In file included from /usr/include/SDL/SDL_main.h:29,
                   from /usr/include/SDL/SDL.h:29,
                   from src/gui/Component.hpp:21,
                   from src/gui/Child.cpp:27:
  /usr/include/SDL/SDL_stdinc.h:135:32: warning: 'SDL_iconv' initialized and declared 'extern'
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                ^~~~~~~~~
  /usr/include/SDL/SDL_stdinc.h:127:21: error: 'iconv_t' was not declared in this scope; did you mean 'ino_t'?
    127 | #define SDL_iconv_t iconv_t
        |                     ^~~~~~~
  /usr/include/SDL/SDL_stdinc.h:135:42: note: in expansion of macro 'SDL_iconv_t'
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                          ^~~~~~~~~~~
  /usr/include/SDL/SDL_stdinc.h:135:58: error: expected primary-expression before 'const'
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                                          ^~~~~
  /usr/include/SDL/SDL_stdinc.h:135:85: error: expected primary-expression before '*' token
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                                                                     ^
  /usr/include/SDL/SDL_stdinc.h:135:86: error: 'inbytesleft' was not declared in this scope
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                                                                      ^~~~~~~~~~~
  /usr/include/SDL/SDL_stdinc.h:135:99: error: expected primary-expression before 'char'
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                                                                                   ^~~~
  /usr/include/SDL/SDL_stdinc.h:135:121: error: expected primary-expression before '*' token
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                                                                                                         ^
  /usr/include/SDL/SDL_stdinc.h:135:122: error: 'outbytesleft' was not declared in this scope
    135 | extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
        |                                                                                                                          ^~~~~~~~~~~~
```

**Comment by lanodan** [comment]
Interestingly, lincity-ng compiles fine and seems to run okay here. I also noticed they recently managed to switch to SDL2: https://github.com/lincity-ng/lincity-ng/pull/40 (which works nicely)

- lincity-ng 2.9-beta, fedora seems to be using https://github.com/lincity-ng/lincity-ng/commit/7f266b1a342e0ba4d34e734ee93029f33b97c69a instead.
- sdl12-compat 7e83bd095f6d67939399a7c8973134945d9060c5 and 4ad7ba6348d08d75496362efab1cbf099a6de42d
- SDL2 https://github.com/libsdl-org/SDL/commit/56e96254c23105d7c7657f32d50661435d838b6a and https://github.com/libsdl-org/SDL/commit/41fab8532d56f8b286195edbc2d9bf270fbe5ca0

**Comment by icculus** [comment]
@sezero I agree on this whole list, next time @Conan-Kudo updates the sdl12-compat package I'm going to re-run all the builds and I think most of this list will resolve then, between the GL and X11 dependency fixes, leaving the ones that need an explicit dependency on the ALSA packages (bugs filed with fedora already) and our own issues still to be fixed.

**Comment by Conan-Kudo** [comment]
The Fedora package has been updated to the current HEAD for both native and MinGW packages. My COPR has auto-built it for Fedora Linux 34 from Rawhide as well. You should be able to do it now. 😉

**Comment by icculus** [comment]
> Interestingly, lincity-ng compiles fine and seems to run okay here.

We fixed things for the final SDL 1.2-based commit of lincity-ng in #54.  :)

**Comment by Conan-Kudo** [comment]
lincity-ng switched to SDL2 just shortly before the SDL1onSDL2 change was proposed in Fedora, and our lincity-ng has more patches than I would like on it. It's been on my list of things to do to rebase it to current HEAD. 😢

**Comment by Conan-Kudo** [comment]
PR to update lincity-ng: https://src.fedoraproject.org/rpms/lincity-ng/pull-request/1

**Comment by icculus** [comment]
Updated list. Logs are all the same so I won't upload them again, but this confirms all the packages that couldn't find OpenGL and X11 are fixed.

At this point, we have a handful of things to fix, and the rest are Fedora packaging bugs.

```
SDL12_COMPAT_FAILED: ClanLib1
SDL12_COMPAT_FAILED: asterisk
SDL12_COMPAT_FAILED: berusky
SDL12_COMPAT_FAILED: fawkes
SDL12_COMPAT_FAILED: glob2
SDL12_COMPAT_FAILED: grafx2
SDL12_COMPAT_FAILED: libzia
SDL12_COMPAT_FAILED: lincity-ng
SDL12_COMPAT_FAILED: mlt
SDL12_COMPAT_FAILED: nagi
SDL12_COMPAT_FAILED: nethack-vultures
SDL12_COMPAT_FAILED: rcssserver3d
SDL12_COMPAT_FAILED: simcoupe
SDL12_COMPAT_FAILED: simspark
SDL12_COMPAT_FAILED: tvtime
SDL12_COMPAT_FAILED: uboot-tools
SDL12_COMPAT_FAILED: xgrav
SDL12_COMPAT_FAILED: xwax
```

**Comment by icculus** [comment]
lincity-ng should build correctly, as of e20b7fc8fe7a17caeb360fd85b19c598bf0c32fb.

**Comment by icculus** [comment]
I believe we're probably at the point where we can close this bug? sdl12-compat is live in the now-released Fedora 35, and the rest of the package issues were things like an explicit, unnecessary dependency on ALSA (etc) that weren't our bugs (and bug reports were filed against all those packages).

**Comment by sezero** [comment]
Indeed, let's close this.

**Comment by Conan-Kudo** [comment]
I'm fine with that.

**Comment by sezero** [comment]
OK, closing.

**Comment by slouken** [comment]
FYI, in the next release you will be able to remove mesa-libGLU-devel as a dependency from sdl12-compat, and add it along with defining `SDL_INCLUDE_GLU_H` for applications that actually require it.
